modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPLv3.0"
issueTrackerURL = "https://github.com/Iskaa303/Guts-Gore/issues"

[[mods]]
    modId = "${modId}"
    version = "${modVersion}"
    displayName = "${modName}"
    credits = "By Iskaa303, and many others."
    authors = "Iskaa303"
    description = '''A modular limb system for living entities.'''

[[dependencies.${modId}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforgeVersionRange}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modId}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraftVersionRange}"
    ordering = "NONE"
    side = "BOTH"
